# Generated by Django 3.1 on 2023-08-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biryani_type',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
