# Generated by Django 3.1 on 2023-08-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20230802_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biryani_type',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='biryani_type',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
